name: Create Release

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'
                  cache-dependency-path: ./src/package-lock.json

            - name: Install dependencies build and dist
              run: |
                  ls -la
                  npm i
                  npm run release
              working-directory: ./src

            - name: Upload release dist file
              uses: actions/upload-artifact@v4
              with:
                  path: ./src/dist
                  name: dist

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Get Version
              id: get_version
              run: |
                  echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
                  echo "FORMATTED_VERSION=$(jq -r .version package.json | tr '.' '-')" >> $GITHUB_ENV
              working-directory: ./src

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ env.VERSION }}
                  release_name: Release ver${{ env.VERSION }}
                  body_path: ./RELEASE.md
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Set Upload Url
              id: set_upload_url
              run: echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> "$GITHUB_ENV"

            - name: Download dist artifact
              uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: ./src/dist

            - name: Check dist artifact
              run: |
                  ls -la ./src
                  ls -la ./src/dist

            - name: Create Release Asset
              id: create_release_asset
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ env.UPLOAD_URL }}
                  asset_path: ./src/dist/ViewInventory_${{ env.FORMATTED_VERSION }}.mcaddon
                  asset_name: ViewInventory_${{ env.FORMATTED_VERSION }}.mcaddon
                  asset_content_type: application/zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
